version: "3.9"

services:
  backend:
    build:
      context: .
    image: ${DOCKERHUB_USER:-local}/apis-ia-backend:latest
    container_name: apis-ia-backend
    ports:
      - "8085:8085"
    networks:
      - be-net

networks:
  be-net:
    driver: bridge
